### ISSUE TITLE
how to run in docker container ?

### ISSUE THREAD

**Issue by zhongwenkun886** [TalkUHulk/ai.deploy.box#2]
After "docker pull mister5ive/ai.deploy.box" and enter into the container, how to run the samples? I can not find any code.

**Comment by TalkUHulk** [comment]
> After "docker pull mister5ive/ai.deploy.box" and enter into the container, how to run the samples? I can not find any code.

clone this rep

**Comment by zhongwenkun886** [comment]
OK， thanks
