### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by taojishou** [TalkUHulk/ai.deploy.box#4]
[ 92%] Linking CXX shared library libAiDB.so
/usr/bin/ld: 找不到 -lMNN: 没有那个文件或目录
/usr/bin/ld: 找不到 -lonnxruntime: 没有那个文件或目录
/usr/bin/ld: 找不到 -lncnn: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make[2]: *** [source/CMakeFiles/AiDB.dir/build.make:821：source/libAiDB.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:129：source/CMakeFiles/AiDB.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 93%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/wrapper/AiDBYoloV8Node.cpp.o
[ 94%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/wrapper/AiDBYoloXNode.cpp.o
[ 95%] Building CXX object source/CMakeFiles/AiDB_C.dir/__/3rdparty/cpp-base64/base64.cpp.o
[ 96%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/aidb_flow.cpp.o
[ 97%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/aidb_server.cpp.o
[ 98%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/reflect.cpp.o
[ 99%] Building CXX object source/CMakeFiles/AiDB_C.dir/c_api/aidb_c_api.cpp.o
^[a[100%] Linking CXX shared library libAiDB_C.so
/usr/bin/ld: 找不到 -lMNN: 没有那个文件或目录
/usr/bin/ld: 找不到 -lonnxruntime: 没有那个文件或目录
/usr/bin/ld: 找不到 -lncnn: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make[2]: *** [source/CMakeFiles/AiDB_C.dir/build.make:1109：source/libAiDB_C.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:155：source/CMakeFiles/AiDB_C.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
root@tao-H610M-D-EVO-V21:/home/build/ai.deploy.box/build#
环境都下载了

**Comment by TalkUHulk** [comment]
> [ 92%] Linking CXX shared library libAiDB.so /usr/bin/ld: 找不到 -lMNN: 没有那个文件或目录 /usr/bin/ld: 找不到 -lonnxruntime: 没有那个文件或目录 /usr/bin/ld: 找不到 -lncnn: 没有那个文件或目录 collect2: error: ld returned 1 exit status make[2]: *** [source/CMakeFiles/AiDB.dir/build.make:821：source/libAiDB.so] 错误 1 make[1]: *** [CMakeFiles/Makefile2:129：source/CMakeFiles/AiDB.dir/all] 错误 2 make[1]: *** 正在等待未完成的任务.... [ 93%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/wrapper/AiDBYoloV8Node.cpp.o [ 94%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/wrapper/AiDBYoloXNode.cpp.o [ 95%] Building CXX object source/CMakeFiles/AiDB_C.dir/__/3rdparty/cpp-base64/base64.cpp.o [ 96%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/aidb_flow.cpp.o [ 97%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/aidb_server.cpp.o [ 98%] Building CXX object source/CMakeFiles/AiDB_C.dir/server/reflect.cpp.o [ 99%] Building CXX object source/CMakeFiles/AiDB_C.dir/c_api/aidb_c_api.cpp.o ^[a[100%] Linking CXX shared library libAiDB_C.so /usr/bin/ld: 找不到 -lMNN: 没有那个文件或目录 /usr/bin/ld: 找不到 -lonnxruntime: 没有那个文件或目录 /usr/bin/ld: 找不到 -lncnn: 没有那个文件或目录 collect2: error: ld returned 1 exit status make[2]: *** [source/CMakeFiles/AiDB_C.dir/build.make:1109：source/libAiDB_C.so] 错误 1 make[1]: *** [CMakeFiles/Makefile2:155：source/CMakeFiles/AiDB_C.dir/all] 错误 2 make: *** [Makefile:91：all] 错误 2 root@tao-H610M-D-EVO-V21:/home/build/ai.deploy.box/build# 环境都下载了

看提示是link错误，可以确认下LIB_PATH路径下有没有so库
