### ISSUE TITLE
大佬，想问一下，PPOCRV3如何转换为的MNN，维度有设置吗

### ISSUE THREAD

**Issue by ff-0028** [TalkUHulk/ai.deploy.box#5]
大佬，想问一下，PPOCRV3如何转换为的MNN，维度有设置吗

**Comment by TalkUHulk** [comment]
> 大佬，想问一下，PPOCRV3如何转换为的MNN，维度有设置吗

指令如下：

`MNNConvert -f ONNX --modelFile ch_PP-OCRv3_rec.onnx    --MNNModel ch_PP-OCRv3_rec.mnn   --bizCode MNN`

`MNNConvert -f ONNX --modelFile ch_PP-OCRv3_det_infer.onnx   --MNNModel ch_PP-OCRv3_det_infer.mnn  --bizCode MNN`

**Comment by ff-0028** [comment]
万分感谢
