### ISSUE TITLE
safetensor如何转何转为四个onnx模型

### ISSUE THREAD

**Issue by wangzijian1010** [TalkUHulk/ai.deploy.box#6]
大佬你好 非常优秀的工作 我是从公众号上看到来这个repo的 感谢大佬无偿分享知识 在公众号中`optimum-cli export onnx —task stable-diffusion  —model stable-diffusion-inpainting stable-diffusion-inpainting-onnx` 得到4个onnx模型 是我在c站上任意下载safetensors文件然后使用上述代码都可以得到四个组件的onnx文件吗 期待大佬回复

**Comment by TalkUHulk** [comment]
> 大佬你好 非常优秀的工作 我是从公众号上看到来这个repo的 感谢大佬无偿分享知识 在公众号中`optimum-cli export onnx —task stable-diffusion —model stable-diffusion-inpainting stable-diffusion-inpainting-onnx` 得到4个onnx模型 是我在c站上任意下载safetensors文件然后使用上述代码都可以得到四个组件的onnx文件吗 期待大佬回复

应该不是任意都可以吧，optimum似乎还不支持LoRa的export

**Comment by wangzijian1010** [comment]
> > 大佬你好 非常优秀的工作 我是从公众号上看到来这个repo的 感谢大佬无偿分享知识 在公众号中`optimum-cli export onnx —task stable-diffusion —model stable-diffusion-inpainting stable-diffusion-inpainting-onnx` 得到4个onnx模型 是我在c站上任意下载safetensors文件然后使用上述代码都可以得到四个组件的onnx文件吗 期待大佬回复
> 
> 应该不是任意都可以吧，optimum似乎还不支持LoRa的export

也就是不带Lora的safetensor可以直接通过optimum导出为onnx是吧大佬

**Comment by TalkUHulk** [comment]
> > > 大佬你好 非常优秀的工作 我是从公众号上看到来这个repo的 感谢大佬无偿分享知识 在公众号中`optimum-cli export onnx —task stable-diffusion —model stable-diffusion-inpainting stable-diffusion-inpainting-onnx` 得到4个onnx模型 是我在c站上任意下载safetensors文件然后使用上述代码都可以得到四个组件的onnx文件吗 期待大佬回复
> > 
> > 
> > 应该不是任意都可以吧，optimum似乎还不支持LoRa的export
> 
> 也就是不带Lora的safetensor可以直接通过optimum导出为onnx是吧大佬

有段时间没看sd的东西了，印象里是不支持lora的，但简单改改代码，controlnet、lora这些都可以转。理论上都可以

**Comment by TalkUHulk** [comment]
> > > 大佬你好 非常优秀的工作 我是从公众号上看到来这个repo的 感谢大佬无偿分享知识 在公众号中`optimum-cli export onnx —task stable-diffusion —model stable-diffusion-inpainting stable-diffusion-inpainting-onnx` 得到4个onnx模型 是我在c站上任意下载safetensors文件然后使用上述代码都可以得到四个组件的onnx文件吗 期待大佬回复
> > 
> > 
> > 应该不是任意都可以吧，optimum似乎还不支持LoRa的export
> 
> 也就是不带Lora的safetensor可以直接通过optimum导出为onnx是吧大佬

有段时间没看sd的东西了，印象里是不支持lora的，但简单改改代码，controlnet、lora这些都可以转。标准的sd理论上都可以用optimum直接导出的

**Comment by wangzijian1010** [comment]
> > > > 大佬你好 非常优秀的工作 我是从公众号上看到来这个repo的 感谢大佬无偿分享知识 在公众号中`optimum-cli export onnx —task stable-diffusion —model stable-diffusion-inpainting stable-diffusion-inpainting-onnx` 得到4个onnx模型 是我在c站上任意下载safetensors文件然后使用上述代码都可以得到四个组件的onnx文件吗 期待大佬回复
> > > 
> > > 
> > > 应该不是任意都可以吧，optimum似乎还不支持LoRa的export
> > 
> > 
> > 也就是不带Lora的safetensor可以直接通过optimum导出为onnx是吧大佬
> 
> 有段时间没看sd的东西了，印象里是不支持lora的，但简单改改代码，controlnet、lora这些都可以转。标准的sd理论上都可以用optimum直接导出的

好的 感谢大佬回复 感谢感谢 大佬工作顺利！
